### ISSUE TITLE
Markdown for better readability

### ISSUE THREAD

**Issue by shubham1172** [AnmolTomer/nodejs_murphy#1]
I suggest using markdown over text files for making notes.
Markdown gets rendered nicely by GitHub and you can have hyperlinks and fancy formatting.

**Comment by AnmolTomer** [comment]
Thank a lot for pointing that out. I wasn't aware of it. Working towards closing this issue. 😄 👍

**Comment by AnmolTomer** [comment]
Done changes to txt files, added README. Feel free to suggest further improvements.

**Comment by shubham1172** [comment]
You can link your files to provide better navigation. For example in the [README](https://github.com/AnmolTomer/nodejs_murphy/#contents), you can have something like:

1. [Quick Intro to Course 2. What is Node (part 1)](./01.%20quick_intro_to_course.md)
